### ISSUE TITLE
Div usage

### ISSUE THREAD

**Issue by farishkash** [diwuwudi/prj-rev-bwfs-dasmoto#2]
Consider using divs to organize each section of content.  The purpose of the div is to act as a block container for each section.  It will allow to use classes to apply repeatable css classes to you can style multiple divs the same.  It also allows you create unique sections of content using what I mention above.

As you progress through the course, you will see a lot of div usage, in fact for certain features you have to use divs to make in manageable.

```
<div>
<h2 class="frames">Frames</h2>
    <img src="./resources/frames.jpeg" />
    <h3>Art Frames (assorted)</h3>
    <p>Assorted frames made of different material, including MDF, birchwood, and
      PDE. Select frames can be sanded and painted according to your needs.
      <strong>Starting at $2.00 / frame</strong>.</p>
</div>
```

**Comment by diwuwudi** [comment]
Thanks :)
