### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [diwuwudi/prj-rev-bwfs-dasmoto#3]
Overall excellent.  In this initial project I look at two items, first did you use divs to manage each section of content.  Was your css overly repetitive.

First yes you didn't use divs, but your html was well organized, this is more of a point of emphasis to prepare you for future projects. 

Second your css wasn't overly repetitive, I know I brought up the use of strong vs span, but this was more an informational item that I wanted to pass along to you.

To prepare you for the upcoming projects, look at bootstrap, getbootstrap.com.  See if you can add it to this site and use some of the classes in here.  It will teach you some concepts that will be used in the upcoming projects.

**Comment by diwuwudi** [comment]
Thanks very much for your feedback :)
